package ua.mike.pub.dto;

public enum OrderStatus {

    NEW, VALIDATION_PENDING, VALIDATED, VALIDATION_ERROR,
    ALLOCATION_PENDING, ALLOCATED, ALLOCATION_ERROR,
    INVENTORY_PENDING, PICKED_UP, CANCELED
}
